# TUGAS pipelines

In [ ]:
import pandas as pd

In [ ]:
%cd /content/drive/MyDrive/sainsdata/tugas/

/content/drive/MyDrive/sainsdata/tugas


In [ ]:
df = pd.read_csv('Data/data_sqlServer.csv')
print(df)

     sepallength  sepalwidth  petallength  petalwidth           class
0              6         4.0          1.2         0.2     Iris-setosa
1              6         4.4          1.5         0.4     Iris-setosa
2              6         3.8          1.7         0.3     Iris-setosa
3              6         4.2          1.4         0.2     Iris-setosa
4              6         3.5          1.3         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145            7         3.1          5.6         2.4  Iris-virginica
146            7         3.1          5.1         2.3  Iris-virginica
147            7         3.2          5.9         2.3  Iris-virginica
148            7         3.3          5.7         2.5  Iris-virginica
149            7         3.0          5.2         2.3  Iris-virginica

[150 rows x 5 columns]


In [ ]:
data_SqlServer= df.drop(['sepallength','sepalwidth','petallength'],axis=1)
# data_SqlServer.insert(0, 'id', range(1, 1 + len(df)))
print(data_SqlServer)

     petalwidth           class
0           0.2     Iris-setosa
1           0.4     Iris-setosa
2           0.3     Iris-setosa
3           0.2     Iris-setosa
4           0.2     Iris-setosa
..          ...             ...
145         2.4  Iris-virginica
146         2.3  Iris-virginica
147         2.3  Iris-virginica
148         2.5  Iris-virginica
149         2.3  Iris-virginica

[150 rows x 2 columns]


In [ ]:
# # enghine.create_engine('mysql://root@localhost/prosain{200411100153}')
# engine = db.create_engine('mysql://root@localhost/prosain{200411100153}')
# connection = engine.connect()
# metadata = db.MetaData()
# census = db.Table('census', metadata, autoload=True, autoload_with=engine)
df = pd.read_csv('Data/data_postgresSql.csv')
print(df)

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
data_postgreSQL= df.drop(['sepalwidth','petallength','petalwidth','class'],axis=1)
# data_postgreSQL.insert(0, 'id', range(1, 1 + len(df)))
print(data_postgreSQL)

     sepallength
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0
..           ...
145          6.7
146          6.3
147          6.5
148          6.2
149          5.9

[150 rows x 1 columns]


In [ ]:
# import orchest
# connection_string = f"mysql://root:@{orchest.get_service('mysql')['localhost']}/postgres"


In [ ]:
import psycopg2
import pandas as pd

In [ ]:
conn = psycopg2.connect(user="omzodijx",
                        password="pLWoH_9dKprmXqsvNx2UFFxhLTOQtNG4",
                        host="floppy.db.elephantsql.com",database="omzodijx")
cursor = conn.cursor()


In [ ]:
cursor.execute("SELECT * FROM iriss")
data = cursor.fetchall()
print(data)

[('sepallegth', 'sepalwidth', 'petallegth', 'petalwidth', 'class'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '3', '1', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '3', '1', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('4', '3', '1', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '3', '1', '0', 'Iris-setosa'), ('4', '3', '1', '0', 'Iris-setosa'), ('6', '4', '1', '0', 'Iris-setosa'), ('6', '4', '2', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('6', '4', '2', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '3', '2', '1', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '

In [ ]:
column = data.pop(0)
print(column)

('sepallegth', 'sepalwidth', 'petallegth', 'petalwidth', 'class')


In [ ]:
column = list(column)
df = pd.DataFrame(data,columns=column)
print(df)

    sepallegth sepalwidth petallegth petalwidth           class
0            5          4          1          0     Iris-setosa
1            5          3          1          0     Iris-setosa
2            5          3          2          0     Iris-setosa
3            5          4          1          0     Iris-setosa
4            5          4          2          0     Iris-setosa
..         ...        ...        ...        ...             ...
144          7          3          5          2  Iris-virginica
145          6          3          5          2  Iris-virginica
146          7          3          5          2  Iris-virginica
147          6          3          5          2  Iris-virginica
148          6          3          5          2  Iris-virginica

[149 rows x 5 columns]


In [ ]:
data_postgreSQLCloud= df.drop(['sepallegth','petallegth','petalwidth','class'],axis=1)
# data_postgreSQLCloud.insert(0, 'id', range(1, 1 + len(df)))
data_postgreSQLCloud['sepalwidth'] = pd.to_numeric(data_postgreSQLCloud['sepalwidth'])
print(data_postgreSQLCloud)

     sepalwidth
0             4
1             3
2             3
3             4
4             4
..          ...
144           3
145           3
146           3
147           3
148           3

[149 rows x 1 columns]


In [ ]:
df = pd.read_csv('Data/data_mysql.csv')
# print(df)
# # import pyodbc 
# # from pyodbc  import connect
# import pymysql
# pymysql.install_as_MySQLdb()
# import _mysql
# conn= _mysql.connect(host="180.253.167.14", user="prosain", passwd="qwerty123", db="prosain{200411100153")


In [ ]:
data_Mysql= df.drop(['sepallength','sepalwidth','petalwidth','class'],axis=1)
# data_Mysql.insert(0, 'id', range(1, 1 + len(df)))
print(data_Mysql)

     petallength
0            1.4
1            1.4
2            1.3
3            1.5
4            1.4
..           ...
145          5.2
146          5.0
147          5.2
148          5.4
149          5.1

[150 rows x 1 columns]


In [ ]:
# import orchest
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
# from ipynb.fs.full.PostgresSQLlocal import *
# from ipynb.fs.full.PostgresSQLcloud import *
# from ipynb.fs.full.MySQLlocal import *
# from ipynb.fs.full.SQLServer import *

# print(data_postgreSQL)
new_data_iris = pd.concat([data_postgreSQL,data_postgreSQLCloud,data_Mysql,data_SqlServer],axis=1)
new_data_iris['class'] = pd.Categorical(new_data_iris['class'])
new_data_iris["class"] = new_data_iris["class"].cat.codes
df_data = new_data_iris.values[:, 0:4]
df_target = new_data_iris.values[:, 4]
new_data_iris = new_data_iris.drop(columns=["class"])
# print(type(new_data_iris))


# df_datatarget = new_data_iris.drop(['class'],axis=1)
# df_data = new_data_iris
# print(df_datatarget)
# print(df_data)
# Explicitly cache the data in the "/data" directory since the
# kernel is running in a Docker container, which are stateless.
# The "/data" directory is a special directory managed by Orchest
# to allow data to be persisted and shared across pipelines and
# even projects.
# print("Dowloading California housing data...")
# data = datasets.fetch_california_housing(data_home="/data")
# print(df_data)
# print(df_target)
# Convert the data into a DataFrame.
# df_data = pd.DataFrame(data["data"], columns=data["feature_names"])
# df_target = pd.DataFrame(data["target"], columns=["MedHouseVal"])
# print(df_target)
# Output the housing data so the next steps can retrieve it.
# print("Outputting converted housing data...")
# orchest.output((df_data, df_target), name="data")
# print("Success!")


In [ ]:
df_data

array([[5.1, 4. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.4],
       [4.7, 3. , 1.3, 0.3],
       [4.6, 4. , 1.5, 0.2],
       [5. , 4. , 1.4, 0.2],
       [5.4, 3. , 1.7, 1.5],
       [4.6, 3. , 1.4, 1.3],
       [5. , 3. , 1.5, 1.5],
       [4.4, 3. , 1.4, 1.3],
       [4.9, 4. , 1.5, 1.6],
       [5.4, 3. , 1.5, 1.5],
       [4.8, 3. , 1.6, 1. ],
       [4.8, 3. , 1.4, 1.4],
       [4.3, 4. , 1.1, 1.3],
       [5.8, 4. , 1.2, 1.5],
       [5.7, 4. , 1.5, 1. ],
       [5.4, 4. , 1.3, 1.5],
       [5.1, 4. , 1.4, 1.1],
       [5.7, 4. , 1.7, 1.8],
       [5.1, 3. , 1.5, 1.3],
       [5.4, 4. , 1.7, 1.5],
       [5.1, 4. , 1.5, 1.2],
       [4.6, 3. , 1. , 1.3],
       [5.1, 3. , 1.7, 1.5],
       [4.8, 3. , 1.9, 1. ],
       [5. , 3. , 1.6, 1.1],
       [5. , 4. , 1.6, 1. ],
       [5.2, 3. , 1.5, 1.2],
       [5.2, 3. , 1.4, 1.6],
       [4.7, 3. , 1.6, 1.6],
       [4.8, 3. , 1.6, 1.3],
       [5.4, 4. , 1.5, 1.3],
       [5.2, 4. , 1.5, 1.3],
       [5.5, 3. , 1.4, 1.2],
       [4.9, 3

In [ ]:
nef_df = np.nan_to_num(df_data)

In [ ]:
nef_df

array([[5.1, 4. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.4],
       [4.7, 3. , 1.3, 0.3],
       [4.6, 4. , 1.5, 0.2],
       [5. , 4. , 1.4, 0.2],
       [5.4, 3. , 1.7, 1.5],
       [4.6, 3. , 1.4, 1.3],
       [5. , 3. , 1.5, 1.5],
       [4.4, 3. , 1.4, 1.3],
       [4.9, 4. , 1.5, 1.6],
       [5.4, 3. , 1.5, 1.5],
       [4.8, 3. , 1.6, 1. ],
       [4.8, 3. , 1.4, 1.4],
       [4.3, 4. , 1.1, 1.3],
       [5.8, 4. , 1.2, 1.5],
       [5.7, 4. , 1.5, 1. ],
       [5.4, 4. , 1.3, 1.5],
       [5.1, 4. , 1.4, 1.1],
       [5.7, 4. , 1.7, 1.8],
       [5.1, 3. , 1.5, 1.3],
       [5.4, 4. , 1.7, 1.5],
       [5.1, 4. , 1.5, 1.2],
       [4.6, 3. , 1. , 1.3],
       [5.1, 3. , 1.7, 1.5],
       [4.8, 3. , 1.9, 1. ],
       [5. , 3. , 1.6, 1.1],
       [5. , 4. , 1.6, 1. ],
       [5.2, 3. , 1.5, 1.2],
       [5.2, 3. , 1.4, 1.6],
       [4.7, 3. , 1.6, 1.6],
       [4.8, 3. , 1.6, 1.3],
       [5.4, 4. , 1.5, 1.3],
       [5.2, 4. , 1.5, 1.3],
       [5.5, 3. , 1.4, 1.2],
       [4.9, 3

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(nef_df, df_target, test_size=0.20)

In [ ]:
# import orchest
# from sklearn.model_selection import train_test_split
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import MinMaxScaler

# # Retrieve the data from the previous step.
# data = orchest.get_inputs() 
# data = [(df_data, df_target)]
# X, y = data["data"]

# Print messages are useful when you are keeping an eye on the logs of
# a pipeline step.
# print("Scaling the data...")

# scaler = MinMaxScaler()

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
# df_data.dropna(axis=1)

In [ ]:
# import pandas as pd
# from numpy import nan
# l1 = df_data
# l2 = [item for item in l1 if not(df_data.isnan(item)) == True]
# l2
X_test

array([[7.1, 3. , 5.9, 0.2],
       [6.8, 3. , 5.9, 2.3],
       [5.8, 3. , 5.1, 2. ],
       [6.7, 3. , 5.2, 2.4],
       [5.1, 3. , 1.7, 1.5],
       [5.4, 4. , 1.5, 1.3],
       [5.6, 3. , 4.1, 0.5],
       [5.5, 3. , 1.4, 1.2],
       [4.8, 3. , 1.6, 1. ],
       [5.1, 3. , 3. , 0.1],
       [7.4, 4. , 6.1, 1.8],
       [7.7, 3. , 6.7, 1.4],
       [4.9, 3. , 1.4, 0.4],
       [6.5, 3. , 5.8, 0.3],
       [6.2, 3. , 4.3, 0.1],
       [7.2, 3. , 5.8, 1.7],
       [6. , 3. , 5.1, 0.3],
       [6.5, 3. , 5.1, 0.2],
       [6.3, 3. , 4.9, 0.2],
       [7.7, 3. , 6.7, 1.7],
       [6.5, 4. , 5.5, 1.3],
       [6.3, 3. , 6. , 0.1],
       [5.1, 3. , 1.5, 1.3],
       [5.6, 3. , 4.9, 1.4],
       [4.8, 4. , 1.4, 2. ],
       [4.8, 3. , 1.4, 1.4],
       [5. , 4. , 1.4, 0.2],
       [6.1, 3. , 4.9, 2.1],
       [5.5, 3. , 4. , 1.8],
       [4.9, 3. , 4.5, 0.6]])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler



In [ ]:
import pandas as pd

# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
X_train

array([[6.7, 3. , 5.6, 1.6],
       [4.8, 3. , 1.4, 1.4],
       [4.9, 3. , 3.3, 2.2],
       [5.1, 4. , 1.4, 1.1],
       [6.4, 3. , 5.3, 1. ],
       [4.4, 3. , 1.4, 1.3],
       [4.9, 4. , 1.5, 1.6],
       [5.7, 3. , 4.5, 1.8],
       [6. , 3. , 5. , 1.4],
       [6.6, 3. , 4.6, 1.5],
       [5.1, 4. , 1.5, 1.2],
       [5.4, 4. , 1.3, 1.5],
       [5.6, 3. , 4.2, 0.2],
       [6.3, 3. , 5.6, 2.3],
       [5.7, 3. , 4.2, 0.2],
       [6.7, 2. , 4.7, 0.4],
       [6.2, 3. , 4.8, 1.1],
       [5.7, 2. , 3.5, 0.2],
       [6.7, 3. , 5.7, 2.1],
       [6.9, 3. , 5.4, 1.8],
       [5.2, 4. , 1.5, 1.3],
       [5. , 2. , 1.3, 1.3],
       [4.9, 3. , 1.4, 0.4],
       [5.4, 4. , 1.7, 1.5],
       [6.4, 3. , 4.5, 1.5],
       [6.9, 3. , 5.7, 1.4],
       [6.3, 2. , 4.7, 2.1],
       [5.4, 3. , 1.5, 1.5],
       [6.4, 3. , 5.6, 2.1],
       [5.1, 3. , 1.6, 1.9],
       [6.6, 3. , 4.4, 0.2],
       [5.1, 4. , 1.4, 0.2],
       [5. , 4. , 1.6, 1. ],
       [5.5, 2. , 3.8, 0.1],
       [6.7, 4

In [ ]:
y_train

array([0., 2., 1., 1., 2., 0., 0., 1., 0., 1., 2., 1., 1., 2., 2., 1., 0.,
       2., 2., 2., 0., 2., 2., 0., 2., 1., 1., 2., 0., 2., 1., 0., 1., 2.,
       1., 2., 1., 2., 0., 2., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 2., 2., 0., 1., 2., 0., 2., 0., 1., 2., 0., 1., 2.,
       1., 0., 0., 2., 2., 0., 2., 1., 1., 1., 1., 2., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 2., 2., 0., 2., 0., 2., 0., 0., 2., 0., 1., 0., 1.,
       1., 2., 0., 2., 0., 1., 0., 2., 2., 2., 0., 1., 2., 2., 2., 1., 2.,
       1.])

# Linear Reqression

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score


In [ ]:
# X_test.dropna(axis=0)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Make a prediction and determine the error.
y_test_prediction = np.round(model.predict(X_test))
print(y_test_prediction)
# test_rmse_lr =model.score(X_test,y_test)
test_rmse_lr = np.sqrt(accuracy_score(y_test, y_test_prediction))

[ 1.  2.  1.  0.  1.  2. -0.  1.  2.  0.  1.  2.  2.  1.  1.  2.  2.  2.
  0.  1.  1.  2.  2.  0.  2.  2.  2.  1.  1.  1.]


# Decision Tree

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor
# Fit model.
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [ ]:
# Make a prediction and determine the error.
y_test_prediction = model.predict(X_test)
test_rmse_dt = np.sqrt(accuracy_score(y_test, y_test_prediction))

# Svr

In [ ]:
from sklearn.metrics import accuracy_score,mean_squared_error
from sklearn.svm import SVR
# Fit model.
model = SVR()
model.fit(X_train, y_train.ravel())

SVR()

In [ ]:
# Make a prediction and determine the error.
y_test_prediction = model.predict(X_test)
y_test_prediction = (np.round(y_test_prediction))
print(y_test_prediction)
test_rmse_svm = np.sqrt(accuracy_score(y_test, y_test_prediction))

[ 1.  2.  1.  0.  1.  2. -0.  1.  2.  0.  1.  2.  2.  1.  1.  2.  2.  2.
  0.  1.  1.  2.  1.  0.  2.  2.  2.  1.  1.  1.]


# Result

In [ ]:
print(f'linear-regression-rmse : {test_rmse_lr}')
print(f'decision-tree-regressor-rmse : {test_rmse_dt}')
print(f'svm-regressor-rmse  : {test_rmse_svm}')

linear-regression-rmse : 1.0
decision-tree-regressor-rmse : 0.983192080250175
svm-regressor-rmse  : 0.983192080250175
