# Pipelines with PCA

## Get data

In [ ]:
import pandas as pd

In [ ]:
%cd /content/drive/MyDrive/sainsdata/tugas/

/content/drive/MyDrive/sainsdata/tugas


### Sql server

In [ ]:
df = pd.read_csv('Data/data_sqlServer.csv')
print(df)

     sepallength  sepalwidth  petallength  petalwidth           class
0              6         4.0          1.2         0.2     Iris-setosa
1              6         4.4          1.5         0.4     Iris-setosa
2              6         3.8          1.7         0.3     Iris-setosa
3              6         4.2          1.4         0.2     Iris-setosa
4              6         3.5          1.3         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145            7         3.1          5.6         2.4  Iris-virginica
146            7         3.1          5.1         2.3  Iris-virginica
147            7         3.2          5.9         2.3  Iris-virginica
148            7         3.3          5.7         2.5  Iris-virginica
149            7         3.0          5.2         2.3  Iris-virginica

[150 rows x 5 columns]


In [ ]:
data_SqlServer= df.drop(['sepallength','sepalwidth','petallength'],axis=1)
# data_SqlServer.insert(0, 'id', range(1, 1 + len(df)))
print(data_SqlServer)

     petalwidth           class
0           0.2     Iris-setosa
1           0.4     Iris-setosa
2           0.3     Iris-setosa
3           0.2     Iris-setosa
4           0.2     Iris-setosa
..          ...             ...
145         2.4  Iris-virginica
146         2.3  Iris-virginica
147         2.3  Iris-virginica
148         2.5  Iris-virginica
149         2.3  Iris-virginica

[150 rows x 2 columns]


In [ ]:
# import orchest
# connection_string = f"mysql://root:@{orchest.get_service('mysql')['localhost']}/postgres"


### Mysql cloud

In [ ]:
!pip install mysql-connector-python

In [ ]:
import mysql.connector
mydb = mysql.connector.connect(
  host="sql10.freemysqlhosting.net",
  user="sql10605964",
  password="HlZVvJbmQQ",
  database = "sql10605964"
)
cursor = mydb.cursor()
cursor.execute("select * from TABLE1")
result = cursor.fetchall()

column =['sepallength','sepalwidth','petallength','petalwidth','class']
data_sql = pd.DataFrame(result,columns =column )
print(data_sql.head())
data_Mysql= data_sql.drop(['sepallength','sepalwidth','petalwidth','class'],axis=1)
data_Mysql['petallength'] = pd.to_numeric(data_Mysql['petallength'])
data_Mysql

  sepallength sepalwidth petallength petalwidth        class
0         5.1        3.5         1.4        0.2  Iris-setosa
1         4.9        3.0         1.4        0.2  Iris-setosa
2         4.7        3.2         1.3        0.2  Iris-setosa
3         4.6        3.1         1.5        0.2  Iris-setosa
4         5.0        3.6         1.4        0.2  Iris-setosa


petallength
0            1.4
1            1.4
2            1.3
3            1.5
4            1.4
..           ...
145          5.2
146          5.0
147          5.2
148          5.4
149          5.1

[150 rows x 1 columns]

### Postgres Cloud

In [ ]:
import psycopg2
import pandas as pd

In [ ]:
conn = psycopg2.connect(user="omzodijx",
                        password="pLWoH_9dKprmXqsvNx2UFFxhLTOQtNG4",
                        host="floppy.db.elephantsql.com",database="omzodijx")
cursor = conn.cursor()


In [ ]:
cursor.execute("SELECT * FROM iriss")
data = cursor.fetchall()
print(data)

[('sepallegth', 'sepalwidth', 'petallegth', 'petalwidth', 'class'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '3', '1', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '3', '1', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('4', '3', '1', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '3', '1', '0', 'Iris-setosa'), ('4', '3', '1', '0', 'Iris-setosa'), ('6', '4', '1', '0', 'Iris-setosa'), ('6', '4', '2', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('6', '4', '2', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '4', '2', '0', 'Iris-setosa'), ('5', '4', '1', '0', 'Iris-setosa'), ('5', '3', '2', '1', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '3', '2', '0', 'Iris-setosa'), ('5', '

In [ ]:
column = data.pop(0)
print(column)

('sepallegth', 'sepalwidth', 'petallegth', 'petalwidth', 'class')


In [ ]:
column = list(column)
df = pd.DataFrame(data,columns=column)
print(df)

    sepallegth sepalwidth petallegth petalwidth           class
0            5          4          1          0     Iris-setosa
1            5          3          1          0     Iris-setosa
2            5          3          2          0     Iris-setosa
3            5          4          1          0     Iris-setosa
4            5          4          2          0     Iris-setosa
..         ...        ...        ...        ...             ...
144          7          3          5          2  Iris-virginica
145          6          3          5          2  Iris-virginica
146          7          3          5          2  Iris-virginica
147          6          3          5          2  Iris-virginica
148          6          3          5          2  Iris-virginica

[149 rows x 5 columns]


In [ ]:
data_postgreSQLCloud= df.drop(['petallength','petalwidth','class'],axis=1)
data_postgreSQLCloud['sepallength'] = pd.to_numeric(data_postgreSQLCloud['sepallength'])
data_postgreSQLCloud['sepalwidth'] = pd.to_numeric(data_postgreSQLCloud['sepalwidth'])

print(data_postgreSQLCloud)

     sepallength  sepalwidth
0            5.1         3.5
1            4.9         3.0
2            4.7         3.2
3            4.6         3.1
4            5.0         3.6
..           ...         ...
145          6.7         3.0
146          6.3         2.5
147          6.5         3.0
148          6.2         3.4
149          5.9         3.0

[150 rows x 2 columns]


In [ ]:
# df = pd.read_csv('Data/data_mysql.csv')
# print(df)
# # import pyodbc 
# # from pyodbc  import connect
# import pymysql
# pymysql.install_as_MySQLdb()
# import _mysql
# conn= _mysql.connect(host="180.253.167.14", user="prosain", passwd="qwerty123", db="prosain{200411100153")


In [ ]:
# data_Mysql= df.drop(['sepallength','sepalwidth','petalwidth','class'],axis=1)
# # data_Mysql.insert(0, 'id', range(1, 1 + len(df)))
# print(data_Mysql)

     petallength
0            1.4
1            1.4
2            1.3
3            1.5
4            1.4
..           ...
145          5.2
146          5.0
147          5.2
148          5.4
149          5.1

[150 rows x 1 columns]


## Collecting Data

In [ ]:
# import orchest
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
# from ipynb.fs.full.PostgresSQLlocal import *
# from ipynb.fs.full.PostgresSQLcloud import *
# from ipynb.fs.full.MySQLlocal import *
# from ipynb.fs.full.SQLServer import *

# print(data_postgreSQL)
new_data_iris = pd.concat([data_postgreSQLCloud,data_Mysql,data_SqlServer],axis=1)
new_data_iris['class'] = pd.Categorical(new_data_iris['class'])
new_data_iris["class"] = new_data_iris["class"].cat.codes
df_data = new_data_iris.values[:, 0:4]
df_target = new_data_iris.values[:, 4]
new_data_iris = new_data_iris.drop(columns=["class"])
# print(type(new_data_iris))


# df_datatarget = new_data_iris.drop(['class'],axis=1)
# df_data = new_data_iris
# print(df_datatarget)
# print(df_data)
# Explicitly cache the data in the "/data" directory since the
# kernel is running in a Docker container, which are stateless.
# The "/data" directory is a special directory managed by Orchest
# to allow data to be persisted and shared across pipelines and
# even projects.
# print("Dowloading California housing data...")
# data = datasets.fetch_california_housing(data_home="/data")
# print(df_data)
# print(df_target)
# Convert the data into a DataFrame.
# df_data = pd.DataFrame(data["data"], columns=data["feature_names"])
# df_target = pd.DataFrame(data["target"], columns=["MedHouseVal"])
# print(df_target)
# Output the housing data so the next steps can retrieve it.
# print("Outputting converted housing data...")
# orchest.output((df_data, df_target), name="data")
# print("Success!")


In [ ]:
df_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.4],
       [4.7, 3.2, 1.3, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 1.5],
       [4.6, 3.4, 1.4, 1.3],
       [5. , 3.4, 1.5, 1.5],
       [4.4, 2.9, 1.4, 1.3],
       [4.9, 3.1, 1.5, 1.6],
       [5.4, 3.7, 1.5, 1.5],
       [4.8, 3.4, 1.6, 1. ],
       [4.8, 3. , 1.4, 1.4],
       [4.3, 3. , 1.1, 1.3],
       [5.8, 4. , 1.2, 1.5],
       [5.7, 4.4, 1.5, 1. ],
       [5.4, 3.9, 1.3, 1.5],
       [5.1, 3.5, 1.4, 1.1],
       [5.7, 3.8, 1.7, 1.8],
       [5.1, 3.8, 1.5, 1.3],
       [5.4, 3.4, 1.7, 1.5],
       [5.1, 3.7, 1.5, 1.2],
       [4.6, 3.6, 1. , 1.3],
       [5.1, 3.3, 1.7, 1.5],
       [4.8, 3.4, 1.9, 1. ],
       [5. , 3. , 1.6, 1.1],
       [5. , 3.4, 1.6, 1. ],
       [5.2, 3.5, 1.5, 1.2],
       [5.2, 3.4, 1.4, 1.6],
       [4.7, 3.2, 1.6, 1.6],
       [4.8, 3.1, 1.6, 1.3],
       [5.4, 3.4, 1.5, 1.3],
       [5.2, 4.1, 1.5, 1.3],
       [5.5, 4.2, 1.4, 1.2],
       [4.9, 3

## Prepocesing PCA

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
X = df_data
X = StandardScaler().fit_transform(X)
y = df_target

In [ ]:
# Run PCA over the features.
pca = PCA(n_components=3)
X = pca.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
# import orchest
# from sklearn.model_selection import train_test_split
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import MinMaxScaler

# # Retrieve the data from the previous step.
# data = orchest.get_inputs() 
# data = [(df_data, df_target)]
# X, y = data["data"]

# Print messages are useful when you are keeping an eye on the logs of
# a pipeline step.
# print("Scaling the data...")

# scaler = MinMaxScaler()

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
# df_data.dropna(axis=1)

In [ ]:
# import pandas as pd
# from numpy import nan
# l1 = df_data
# l2 = [item for item in l1 if not(df_data.isnan(item)) == True]
# l2
X_test

array([[ 1.17560864,  1.27508854,  0.08812173],
       [ 0.17188024,  0.60381562,  0.5517485 ],
       [ 0.36987394,  1.46266434,  0.13646826],
       [-1.60695487,  0.3490416 , -0.52597246],
       [ 0.44872655,  1.17644875,  0.94836875],
       [-1.68656859, -0.04594717,  0.6104394 ],
       [-1.41454166, -0.6353177 ,  0.33834467],
       [ 0.48662826, -1.78112236,  0.21790172],
       [ 0.43875903, -1.25619493, -0.03194642],
       [-1.75330618,  0.42650186, -0.0054668 ],
       [ 0.89126962, -0.96664442, -0.31706688],
       [ 2.33254003, -0.2747933 , -0.94017145],
       [ 0.43661152,  0.99021531,  0.75237446],
       [ 0.0976666 , -0.85598229, -0.38481572],
       [ 0.31137461,  0.19617876,  1.09526183],
       [-1.51987035,  0.20240623, -0.32186806],
       [ 0.81396714, -0.43687915,  1.14049247],
       [ 1.08927998, -0.37094282, -1.04443678],
       [ 0.47165969, -2.05009466,  0.34354439],
       [ 1.26353089,  0.92136857, -0.0834938 ],
       [-1.87212487,  1.26858874, -1.317

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler



In [ ]:
import pandas as pd

# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
X_train

array([[ 1.2025937 ,  0.40785925, -0.08217116],
       [-2.14531321,  1.09790412, -1.78769455],
       [-2.08395398,  0.56861373, -0.88562922],
       [ 1.14670104,  0.7010583 ,  1.46483442],
       [ 0.67109357,  0.46688692,  1.24931089],
       [ 0.47068374, -0.76063603, -1.07969674],
       [-2.0497883 ,  0.9987008 , -1.00232863],
       [ 1.79893079,  0.645847  , -0.92327512],
       [ 1.39775051,  0.92082199, -0.48790409],
       [-2.16102624, -0.11541966, -0.0258292 ],
       [ 0.68324699, -0.73167725, -0.65360141],
       [ 1.07522594,  1.59708582,  0.73294742],
       [ 1.14797113,  1.06654172, -0.50208306],
       [ 0.93931926,  1.41644531,  0.72615996],
       [-0.15949535, -0.46157111,  0.9957191 ],
       [-1.46503423, -1.40692779, -0.18762582],
       [-2.09450221,  0.36278285,  0.87574666],
       [-1.86779798, -0.84920824, -1.39753531],
       [-2.48575845,  0.10002177, -0.36020793],
       [ 0.45024987, -1.81352844,  0.25409815],
       [-1.89417553,  1.02473512, -1.005

In [ ]:
y_train

array([1., 1., 1., 2., 2., 0., 1., 1., 1., 1., 0., 2., 1., 2., 2., 0., 2.,
       0., 1., 0., 1., 2., 2., 0., 2., 0., 2., 0., 1., 2., 0., 0., 1., 0.,
       0., 1., 0., 2., 0., 2., 0., 1., 2., 2., 2., 1., 1., 1., 1., 0., 1.,
       2., 2., 0., 1., 0., 2., 1., 0., 1., 1., 2., 0., 0., 1., 2., 0., 1.,
       1., 1., 2., 2., 2., 2., 1., 2., 1., 1., 1., 0., 1., 2., 2., 0., 2.,
       2., 1., 0., 2., 2., 2., 1., 1., 0., 0., 2., 0., 2., 1., 2., 0., 1.,
       0., 0., 2., 1., 2., 0., 1., 0., 0., 0., 0., 0., 2., 1., 0., 0., 2.,
       1.])

## Linear Reqression

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score


In [ ]:
# X_test.dropna(axis=0)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Make a prediction and determine the error.
y_test_prediction = np.round(model.predict(X_test))
print(y_test_prediction)
# test_rmse_lr =model.score(X_test,y_test)
test_rmse_lr = np.sqrt(accuracy_score(y_test, y_test_prediction))

[ 2.  2.  2.  1.  2.  1.  1.  0.  0.  1.  0.  0.  2.  0.  2.  1.  1.  0.
 -0.  1.  1.  0.  2.  1.  2. -0.  2.  0.  0.  1.]


## Decision Tree

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor
# Fit model.
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [ ]:
# Make a prediction and determine the error.
y_test_prediction = model.predict(X_test)
test_rmse_dt = np.sqrt(accuracy_score(y_test, y_test_prediction))

## SVM

In [ ]:
from sklearn.metrics import accuracy_score,mean_squared_error
from sklearn.svm import SVR
# Fit model.
model = SVR()
model.fit(X_train, y_train.ravel())

SVR()

In [ ]:
# Make a prediction and determine the error.
y_test_prediction = model.predict(X_test)
y_test_prediction = (np.round(y_test_prediction))
print(y_test_prediction)
test_rmse_svm = np.sqrt(accuracy_score(y_test, y_test_prediction))

[ 2.  1.  2. -0.  0.  2.  0.  1. -0.  1.  1.  2.  2.  0.  2.  1.  0.  1.
 -0.  2.  1.  2. -0.  0.  2.  1. -0.  2.  1.  2.]


## Result

In [ ]:
print(f'linear-regression-rmse : {test_rmse_lr}')
print(f'decision-tree-regressor-rmse : {test_rmse_dt}')
print(f'svm-regressor-rmse  : {test_rmse_svm}')

linear-regression-rmse : 1.0
decision-tree-regressor-rmse : 0.9660917830792959
svm-regressor-rmse  : 0.9660917830792959
